import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('S$2 autonomous story, exact passage and PDF', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('textbox', { name: 'Research question' })).toHaveValue(/600 MW/)
  await page.getByRole('button', { name: 'Ask', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your answer · v2' })).toBeVisible()
  await expect(page.getByText('QUALIFIES', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('bought S$0.80', { exact: true })).toBeVisible()
  await expect(page.getByText('SKIP_REWRITE', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('SKIP_OVER_CAP', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('sha-256 verified', { exact: false }).first()).toBeVisible()
  await page.getByRole('button', { name: /Citation .*Grid Operators/ }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog').locator('mark')).toContainText(/240|14 months/)
  await page.getByRole('button', { name: 'Close source passage' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download report' }).click()
  const file = await (await download).path()
  expect(file).not.toBeNull()
  expect((await readFile(file!)).subarray(0, 5).toString()).toBe('%PDF-')
  const corpus = await page.request.get('/data/corpus/resources.json')
  expect(corpus.status()).toBe(403)
  expect(await corpus.text()).not.toContain('240 of the 600')
})
