import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('S$2 autonomous story, exact passage and PDF', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('textbox', { name: 'Your question' })).toHaveValue(/600 MW/)
  await page.getByRole('button', { name: /^Ask/ }).click()
  await expect(page.getByRole('heading', { name: 'Your answer · v2' })).toBeVisible()
  const stage = page.getByRole('navigation', { name: 'Research stage' })
  await expect(stage.getByRole('button', { name: 'Answer', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('textbox', { name: 'Your question' })).toBeHidden()
  await expect(page.getByRole('button', { name: 'New question', exact: true })).toBeVisible()
  await expect(page.getByText('QUALIFIES', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('bought S$0.80', { exact: true })).toBeVisible()
  await expect(page.getByText('SKIP_REWRITE', { exact: true }).first()).toBeHidden()
  await expect(page.getByText('SKIP_OVER_CAP', { exact: true }).first()).toBeHidden()
  await stage.getByRole('button', { name: 'Decisions', exact: true }).click()
  await expect(stage.getByRole('button', { name: 'Decisions', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('SKIP_REWRITE', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('SKIP_OVER_CAP', { exact: true }).first()).toBeVisible()
  await stage.getByRole('button', { name: 'Wire', exact: true }).click()
  await expect(page.getByRole('region', { name: 'HTTP exchange' }).getByText('sha-256 ✓', { exact: true }).first()).toBeVisible()
  await stage.getByRole('button', { name: 'Answer', exact: true }).click()
  await page.getByRole('button', { name: /Citation .*Grid Operators/ }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog').locator('mark')).toContainText(/240|14 months/)
  await page.getByRole('button', { name: 'Close source passage' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download report' }).click()
  const file = await (await download).path()
  expect(file).not.toBeNull()
  expect((await readFile(file!)).subarray(0, 5).toString()).toBe('%PDF-')
  const corpus = await page.request.get('/data/corpus/resources.json')
  expect(corpus.status()).toBe(403)
  expect(await corpus.text()).not.toContain('240 of the 600')
  await page.getByRole('button', { name: 'New question', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Your question' })).toBeVisible()
  await page.getByRole('radio', { name: 'S$0', exact: true }).check()
  await page.getByRole('button', { name: /^Ask/ }).click()
  await expect(page.getByRole('heading', { name: 'Your answer · v1' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Your question' })).toBeHidden()
  // This becomes enabled only after the new run finishes, so no later purchase can be missed.
  await expect(page.getByRole('button', { name: 'New question', exact: true })).toBeEnabled()
  await expect(page.getByRole('region', { name: 'Prompt budget' })).toContainText('Free-only run · no purchases authorized.')
  await expect(page.getByText(/^bought S\$/)).toHaveCount(0)
  await stage.getByRole('button', { name: 'Decisions', exact: true }).click()
  await expect(page.getByText('Would buy · with sufficient budget', { exact: true })).toBeVisible()
  await expect(page.getByText('BUY', { exact: true })).toHaveCount(0)
})
