import { expect, test } from '@playwright/test'

async function continueCanonicalSetup(page: import('@playwright/test').Page, deselectProfiles?: string[]) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Use this example' }).click()
  await expect(page.getByRole('heading', { name: 'Choose what the agent may read.' })).toBeVisible()
  if (deselectProfiles) {
    const profiles = page.locator('.setup-source-option')
    const count = await profiles.count()
    for (let index = 0; index < count; index += 1) {
      const profile = profiles.nth(index)
      const label = await profile.innerText()
      if (deselectProfiles.some((name) => label.includes(name))) await profile.click()
    }
  }
  await page.getByRole('button', { name: 'Continue to budget' }).click()
  await expect(page.getByRole('heading', { name: 'Set the maximum research spend.' })).toBeVisible()
  await page.getByRole('button', { name: 'Continue to review' }).click()
  await expect(page.getByRole('heading', { name: 'Review the research plan' })).toBeVisible()
}

test('unsupported fixture questions stay scoped and editable', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Research question' }).fill('Will clean-energy investment be sustainable in 2028?')
  await page.getByRole('button', { name: 'Send research question' }).click()
  await page.getByRole('button', { name: 'Continue to budget' }).click()
  await page.getByRole('button', { name: 'Continue to review' }).click()
  await expect(page.getByRole('heading', { name: 'Unsupported fixture scope' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Will clean-energy investment be sustainable in 2028?' })).toBeVisible()
  await expect(page.getByRole('alert').getByText(/No fixture evidence was searched or used as an answer/)).toBeVisible()
  await expect(page.getByRole('heading', { name: /previews from approved source profiles/i })).toHaveCount(0)
  await expect(page.getByText('Announced demand and capital commitments support continued expansion.', { exact: true })).toHaveCount(0)
  await expect(page.getByText(/Supported fixture scope/)).toBeVisible()
  await page.getByRole('button', { name: 'Use supported fixture question' }).click()
  await expect(page.getByRole('heading', { name: 'Choose what the agent may read.' })).toBeVisible()
})

test('canonical fixture run makes the budget decisions visible', async ({ page }) => {
  await continueCanonicalSetup(page)
  await page.getByRole('button', { name: 'Approve plan & start research' }).click()
  await page.getByRole('tab', { name: /Sources/ }).click()
  await expect(page.getByRole('heading', { name: '12 previews from approved fixture profiles' })).toBeVisible()
  await expect(page.getByRole('contentinfo').getByText('Evidence map ready. Review the recommendation, then explicitly approve or skip it.')).toBeVisible()
  await page.getByRole('button', { name: /Show .* more sources/ }).click()
  const row = (name: string) => page.locator('.source-row').filter({ hasText: name })
  await row('Northstar Wire').getByRole('button', { name: 'Approve purchase S$0.20', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm purchase S$0.20', exact: true }).click()
  await page.getByRole('dialog', { name: 'Northstar Wire' }).getByLabel('Close evidence drawer').click()
  await row('Circuit Note').getByRole('button', { name: 'Skip S$0.30', exact: true }).click()
  const meridianBuy = row('Grid Operators Report').getByRole('button', { name: 'Approve purchase S$0.80', exact: true })
  if (await meridianBuy.count()) { await meridianBuy.click(); await page.getByRole('button', { name: 'Confirm purchase S$0.80', exact: true }).click(); await page.getByRole('dialog', { name: 'Grid Operators Report' }).getByLabel('Close evidence drawer').click() }
  await row('GridScope Asia').getByRole('button', { name: 'Block', exact: true }).click()
  await expect(page.getByText('GridScope blocked: S$1.40 exceeds the remaining S$1.00.').last()).toBeVisible()
  await page.getByRole('button', { name: 'Answer from available evidence' }).click()
  await expect(page.getByText('Dossier ready. Claims are linked to exact accessible spans.').last()).toBeVisible()
  await expect(page.getByText('FIXTURE RESEARCH · NOT INVESTMENT ADVICE')).toBeVisible()
  await expect(page.getByText('≈ S$1.00', { exact: false }).first()).toBeVisible()
})

test('open evidence can answer without a purchase or purchase modal', async ({ page }) => {
  await continueCanonicalSetup(page, ['Grid Operators Report', 'Northstar Wire', 'Buildout & market context', 'GridScope Asia'])
  await page.getByRole('button', { name: 'Approve plan & start research' }).click()
  await page.getByRole('tab', { name: 'Overview' }).click()
  await expect(page.getByRole('button', { name: 'Answer from available evidence' })).toBeEnabled()
  await page.getByRole('button', { name: 'Answer from available evidence' }).click()
  await expect(page.getByText('Dossier ready. Claims are linked to exact accessible spans.').last()).toBeVisible()
  await expect(page.getByText('Open-source conclusion')).toBeVisible()
  const firstCitation = page.getByRole('button', { name: /Open citation:/ }).first()
  await firstCitation.click()
  await expect(page.getByRole('heading', { name: 'Cited evidence span' })).toBeVisible()
  await expect(page.getByRole('dialog').locator('blockquote')).toHaveCount(1)
  await expect(page.getByRole('dialog', { name: 'Confirm this purchase' })).toHaveCount(0)
  await expect(page.locator('.topbar-budget')).toHaveText('0.20 XRP left')
})

test('premium-only evidence remains limited until a purchase is explicitly approved', async ({ page }) => {
  await continueCanonicalSetup(page, ['Grid Operators Report', 'Public energy & buildout data', 'Technical Systems Review', 'Vertex Compute filings', 'Buildout & market context', 'GridScope Asia'])
  await page.getByRole('button', { name: 'Approve plan & start research' }).click()
  await page.getByRole('tab', { name: 'Overview' }).click()
  const answer = page.getByRole('button', { name: 'Answer from available evidence' })
  await expect(answer).toBeDisabled()
  await expect(page.getByRole('heading', { name: 'Answer is limited' })).toBeVisible()
  await expect(page.locator('.answer-panel').getByText('No readable evidence spans are available yet.', { exact: false })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Confirm this purchase' })).toHaveCount(0)
})

test('budget control accepts XRP and shows the approximate SGD value', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Use this example' }).click()
  await page.getByRole('button', { name: 'Continue to budget' }).click()
  const budgetInput = page.locator('input[type="number"][aria-label="Maximum research spend in XRP"]')
  await expect(budgetInput).toHaveValue('0.2')
  await expect(page.getByText('Current balance', { exact: true })).toBeVisible()
  await expect(page.getByText('Analysis token cap', { exact: false })).toHaveCount(0)
  await expect(page.getByText('≈ S$2.00', { exact: false }).first()).toBeVisible()
  await budgetInput.fill('0.5')
  await expect(page.getByText('≈ S$5.00', { exact: false }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Continue to review' }).click()
  await page.getByRole('button', { name: 'Approve plan & start research' }).click()
  await expect(page.locator('.topbar-budget')).toHaveText('0.50 XRP left')
})

test('premium evidence is protected until its exact purchase', async ({ page }) => {
  await continueCanonicalSetup(page)
  await page.getByRole('button', { name: 'Approve plan & start research' }).click()
  await page.getByRole('tab', { name: /Sources/ }).click()
  await page.getByRole('button', { name: /Show .* more sources/ }).click()
  const row = page.locator('.source-row').filter({ hasText: 'Circuit Note' })
  await row.getByRole('button', { name: /Inspect Circuit Note/ }).click()
  await expect(page.getByText('Full text is protected')).toBeVisible()
  await expect(page.getByText('Only metadata, preview, price, and terms are visible before purchase.')).toBeVisible()
  await expect(page.getByText('Fixture quote · payment simulation only')).toBeVisible()
  await expect(page.locator('p.mono').filter({ hasText: 'No real publisher payment' })).toBeVisible()
  await expect(page.getByText('Two switchgear suppliers said booked orders now extend beyond twelve months')).toHaveCount(0)
})

test('setup stays on the canonical fixture scenario', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Financial Times', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Reuters', { exact: true })).toHaveCount(0)
  await expect(page.getByText('BIS', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /bond market/i })).toHaveCount(0)
  await page.getByRole('button', { name: 'Use this example' }).click()
  await expect(page.getByRole('heading', { name: 'Choose what the agent may read.' })).toBeVisible()
  await expect(page.getByText(/fixture search boundary/i)).toBeVisible()
  await expect(page.getByText('FIXTURE RESEARCH · SYNTHETIC CORPUS', { exact: true })).toBeVisible()
})

test('plan review edits permitted fields and gates execution behind approval', async ({ page }) => {
  await continueCanonicalSetup(page)
  await expect(page.getByRole('heading', { name: '12 previews from approved fixture profiles' })).toHaveCount(0)
  await page.getByRole('radio', { name: /Thesis stress test/i }).check()
  await page.getByText('Advanced plan fields and stop conditions', { exact: true }).click()
  await page.getByLabel('Plan research question').fill('What could invalidate the 2028 capacity thesis?')
  await page.getByLabel('Plan decision').fill('Decide whether to delay the buildout commitment.')
  await page.getByLabel('Plan research horizon').fill('Through 2030')
  await page.getByLabel('Plan step 1 objective').fill('Frame a falsification test before reading sources.')
  await page.getByLabel('Stop condition 1 label').fill('No usable baseline remains')
  await page.getByLabel('Stop condition 1 rule').fill('Stop when the approved profiles contain no readable baseline evidence.')
  await page.getByRole('button', { name: 'Save draft' }).click()
  await expect(page.getByRole('contentinfo').getByText('Draft saved locally. No research, purchase, or charge occurred.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Review the research plan' })).toBeVisible()
  await expect(page.getByLabel('Plan research question')).toHaveValue('What could invalidate the 2028 capacity thesis?')
  await expect(page.getByLabel('Plan decision')).toHaveValue('Decide whether to delay the buildout commitment.')
  await expect(page.getByLabel('Plan research horizon')).toHaveValue('Through 2030')
  await expect(page.getByLabel('Plan step 1 objective')).toHaveValue('Frame a falsification test before reading sources.')
  await expect(page.getByLabel('Stop condition 1 label')).toHaveValue('No usable baseline remains')
  await expect(page.getByLabel('Stop condition 1 rule')).toHaveValue('Stop when the approved profiles contain no readable baseline evidence.')
  await page.getByRole('button', { name: 'Approve plan & start research' }).click()
  await page.getByRole('tab', { name: /Sources/ }).click()
  await expect(page.getByRole('heading', { name: '12 previews from approved fixture profiles' })).toBeVisible()
})
