export type AccessTier = 'OPEN' | 'PREMIUM'
export type Decision = 'BUY' | 'SKIP' | 'BLOCKED' | 'DEFER' | 'PENDING'
export type Phase = 'DRAFT' | 'PLANNING' | 'DISCOVERING' | 'RANKING' | 'READING_OPEN' | 'GAP_ANALYSIS' | 'PURCHASE_PLANNING' | 'PURCHASED' | 'SYNTHESIZING' | 'DOSSIER_READY' | 'CANCELLED'
export type Source = {
  id: string; publisher: string; title: string; date: string; kind: 'ARTICLE' | 'REPORT' | 'DATASET_QUERY'; accessTier: AccessTier;
  priceCents: number; preview: string; tags: string[]; entities: string[]; authority: 'HIGH' | 'MEDIUM' | 'LOW'; originality: 'ORIGINAL' | 'DERIVATIVE';
  familyId: string; familyLabel: string; relevance: number; gapMatch: number; novelty: number; trustNote: string; fixture: true; siteKey?: string; xrpDrops?: number;
  decision?: Decision; reason?: string; purchasedAt?: string; evidenceSpans?: { id: string; label: string; text: string }[];
}
export type Claim = { id: string; text: string; stance: 'SUPPORTS' | 'CHALLENGES' | 'UNCERTAIN'; materiality: 'MATERIAL' | 'CONTEXT'; sourceIds: string[]; familyCount: number; spanIds: string[] }
export type ResearchConfig = {
  question: string;
  decision: string;
  horizon: string;
  tokenLimit: number;
  sourceTypes: string[];
  sourceAllowlist?: string[];
}
export type Run = {
  runId: string; version: number; phase: Phase; paused: boolean; cancelled: boolean; budgetCents: number; spentCents: number;
  sources: Source[]; events: { id: string; type: string; label: string; at: string }[]; gap: { question: string; importance: 'HIGH'; state: 'OPEN' | 'PARTIAL' | 'RESOLVED' };
  thesis: { open: string; afterNorthstar?: string; afterMeridian?: string; current: string }; claims: Claim[]; dossierReady: boolean; llm: { provider: string; status: string; model: string }; semanticStatus: 'precomputed' | 'unavailable';
  config: ResearchConfig;
}

export const QUESTION = 'Is the AI data-centre investment boom sustainable through 2028?'
export const CANONICAL_THESIS = 'Announced demand and capital commitments support continued expansion, but the evidence is concentrated in company statements and does not resolve power-delivery constraints.'
export const AFTER_NORTHSTAR = 'Independent supplier reporting corroborates near-term demand while adding equipment-delivery bottlenecks.'
export const AFTER_MERIDIAN = 'The boom can continue, but operating capacity through 2028 is likely to lag announced spending in grid-constrained markets; interconnection and power availability are more material risks than the open-source baseline suggested.'
export const GAP_QUESTION = 'Independent reporting on grid-connection lead times and whether announced data-centre capacity can become operational by 2028.'

export const sources: Source[] = [
  { id:'company-capex', publisher:'Vertex Compute', title:'FY25 capital plan: capacity follows demand', date:'2026-01-28', kind:'ARTICLE', accessTier:'OPEN', priceCents:0, preview:'Vertex Compute says hyperscaler demand supports a multi-year buildout and outlines a larger capital plan.', tags:['capex','demand','capacity'], entities:['Vertex Compute','hyperscalers'], authority:'HIGH', originality:'ORIGINAL', familyId:'family-company', familyLabel:'Company plans', relevance:94, gapMatch:22, novelty:28, trustNote:'Primary issuer statement; not independent validation.', fixture:true },
  { id:'energy-dataset', publisher:'Singapore Energy Market Authority', title:'Data-centre connection queue and reserve margin', date:'2025-11-04', kind:'DATASET_QUERY', accessTier:'OPEN', priceCents:0, preview:'Public series shows connection requests rising while queue timing and local reserve data remain incomplete.', tags:['grid','interconnection','power','data'], entities:['EMA','Singapore'], authority:'HIGH', originality:'ORIGINAL', familyId:'family-energy', familyLabel:'Public energy data', relevance:89, gapMatch:91, novelty:62, trustNote:'Open primary dataset; lagged and incomplete for 2028.', fixture:true },
  { id:'industry-blog', publisher:'Buildout Weekly', title:'Why the next campus is already spoken for', date:'2026-02-10', kind:'ARTICLE', accessTier:'OPEN', priceCents:0, preview:'An industry blog repeats the company-capex narrative and frames demand as the binding constraint.', tags:['capex','demand','buildout'], entities:['Vertex Compute'], authority:'MEDIUM', originality:'DERIVATIVE', familyId:'family-company', familyLabel:'Company plans', relevance:78, gapMatch:17, novelty:8, trustNote:'Derivative commentary; overlaps Vertex Compute.', fixture:true },
  { id:'northstar-wire', publisher:'Northstar Wire', title:'Suppliers feel the pull of the AI buildout', date:'2026-03-02', kind:'ARTICLE', accessTier:'PREMIUM', priceCents:20, preview:'Supplier interviews point to strong near-term demand, but transformer and switchgear lead times are stretching.', tags:['suppliers','equipment','lead-times','demand'], entities:['Northstar Wire','switchgear'], authority:'HIGH', originality:'ORIGINAL', familyId:'family-northstar', familyLabel:'Supplier reporting', relevance:96, gapMatch:72, novelty:80, trustNote:'Independent wire reporting with supplier comments.', fixture:true },
  { id:'circuit-note', publisher:'Circuit Note', title:'AI campuses: the equipment squeeze', date:'2026-03-04', kind:'ARTICLE', accessTier:'PREMIUM', priceCents:30, preview:'A short newsletter echoes Northstar’s supplier bottleneck framing with little additional sourcing.', tags:['suppliers','equipment','lead-times','demand'], entities:['switchgear'], authority:'LOW', originality:'DERIVATIVE', familyId:'family-northstar', familyLabel:'Supplier reporting', relevance:83, gapMatch:68, novelty:11, trustNote:'Heavily overlaps Northstar Wire; no independent family added.', fixture:true },
  { id:'meridian-ledger', publisher:'The Meridian Ledger', title:'The power is promised. The grid is not.', date:'2026-03-12', kind:'REPORT', accessTier:'PREMIUM', priceCents:80, preview:'Interviews with grid operators and developers complicate the buildout story: interconnection studies, not chips, set the pace in constrained markets.', tags:['grid','interconnection','power','lead-times','capacity'], entities:['grid operators','developers'], authority:'HIGH', originality:'ORIGINAL', familyId:'family-meridian', familyLabel:'Grid operator reporting', relevance:99, gapMatch:100, novelty:97, trustNote:'Independent investigation with operator and developer interviews.', fixture:true },
  { id:'gridscope-asia', publisher:'GridScope Asia', title:'The interconnection queue will decide 2028', date:'2026-03-16', kind:'REPORT', accessTier:'PREMIUM', priceCents:140, preview:'A specialist report offers regional queue benchmarks and project-level interconnection lead times.', tags:['grid','interconnection','queue','capacity'], entities:['GridScope Asia','interconnection'], authority:'HIGH', originality:'ORIGINAL', familyId:'family-gridscope', familyLabel:'Infrastructure specialists', relevance:98, gapMatch:98, novelty:94, trustNote:'High-value specialist source; above the S$1 auto-buy ceiling.', fixture:true },
  { id:'chip-supply', publisher:'Open Semiconductor Index', title:'Accelerator supply normalises, with packaging caveats', date:'2026-02-20', kind:'DATASET_QUERY', accessTier:'OPEN', priceCents:0, preview:'Packaging capacity has improved, though advanced assembly remains a watch point for delivery schedules.', tags:['semiconductors','packaging','supply'], entities:['accelerators'], authority:'MEDIUM', originality:'ORIGINAL', familyId:'family-context', familyLabel:'Semiconductor data', relevance:71, gapMatch:34, novelty:56, trustNote:'Open industry series; context, not a capacity forecast.', fixture:true },
  { id:'cooling-review', publisher:'Thermal Systems Review', title:'Cooling is becoming a site-selection constraint', date:'2026-01-19', kind:'ARTICLE', accessTier:'OPEN', priceCents:0, preview:'A technical review describes cooling and water requirements that can delay dense AI campuses.', tags:['cooling','water','site-selection'], entities:['AI campuses'], authority:'MEDIUM', originality:'ORIGINAL', familyId:'family-context', familyLabel:'Technical constraints', relevance:67, gapMatch:47, novelty:63, trustNote:'Technical context with no project-level delivery data.', fixture:true },
  { id:'financing-note', publisher:'Open Markets Desk', title:'Funding the second wave of compute', date:'2026-02-27', kind:'ARTICLE', accessTier:'OPEN', priceCents:0, preview:'Debt markets remain open for strong sponsors, but construction financing is sensitive to timing and utilisation.', tags:['financing','capex','construction'], entities:['data centres'], authority:'MEDIUM', originality:'ORIGINAL', familyId:'family-context', familyLabel:'Financing context', relevance:64, gapMatch:29, novelty:58, trustNote:'Independent market commentary; no operating-capacity evidence.', fixture:true },
  { id:'construction-index', publisher:'Civic Build Index', title:'Specialty construction labour remains tight', date:'2025-12-18', kind:'DATASET_QUERY', accessTier:'OPEN', priceCents:0, preview:'A public index shows specialist electrical and commissioning labour shortages across major hubs.', tags:['construction','labour','lead-times'], entities:['commissioning'], authority:'HIGH', originality:'ORIGINAL', familyId:'family-context', familyLabel:'Construction data', relevance:70, gapMatch:53, novelty:66, trustNote:'Open primary index; geography is broad.', fixture:true },
  { id:'rewriter-brief', publisher:'Market Signal Digest', title:'AI capex: the trillion-dollar runway', date:'2026-02-01', kind:'ARTICLE', accessTier:'OPEN', priceCents:0, preview:'A market digest compiles public company announcements and repeats the demand thesis.', tags:['capex','demand','hyperscalers'], entities:['hyperscalers'], authority:'LOW', originality:'DERIVATIVE', familyId:'family-company', familyLabel:'Company plans', relevance:74, gapMatch:14, novelty:4, trustNote:'Derivative compilation; adds no independent evidence.', fixture:true },
]

export function normalize(text: string): string[] { return text.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim().split(/\s+/).filter(Boolean) }
export function tfidfScore(query: string, source: Source): number { const q = new Set(normalize(query)); const d = new Set(normalize(`${source.title} ${source.preview} ${source.tags.join(' ')} ${source.entities.join(' ')}`)); return q.size ? [...q].filter((token) => d.has(token)).length / q.size : 0 }
export function rankSources(query = QUESTION, input = sources): Source[] { return [...input].sort((a,b) => (b.relevance + b.gapMatch * 0.2 + tfidfScore(query,b)*20 - (b.originality === 'DERIVATIVE' ? 18 : 0)) - (a.relevance + a.gapMatch * 0.2 + tfidfScore(query,a)*20 - (a.originality === 'DERIVATIVE' ? 18 : 0))) }
export function utility(source: Source, remainingCents: number): number { const value = .24*(source.gapMatch/100)+.18*(source.relevance/100)+.16*(source.authority==='HIGH'?1:source.authority==='MEDIUM'?.65:.35)+.16*(source.novelty/100)+.12*(source.originality==='ORIGINAL'?1:.2)+.10*(source.gapMatch/100)+.04*.8-.20*(source.originality==='DERIVATIVE'?.9:.05); return Math.round(value*1000)/1000 }
