import { expect, test } from '@playwright/test'

test('canonical fixture run makes the budget decisions visible', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'What economic question deserves a closer look?' })).toBeVisible()
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Make the question answerable.' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Select fixture source profiles' })).toBeVisible()
  await page.getByRole('button', { name: 'Start research' }).click()
  await expect(page.getByRole('heading', { name: '12 previews from approved fixture profiles' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Bought the report that closes the grid gap.' })).toBeVisible()
  await page.getByRole('button', { name: /Show .* more sources/ }).click()
  const row = (name: string) => page.locator('.source-row').filter({ hasText: name })
  await row('Northstar Wire').getByRole('button', { name: 'Buy S$0.20', exact: true }).click()
  await row('Circuit Note').getByRole('button', { name: 'Skip S$0.30', exact: true }).click()
  const meridianBuy = row('Grid Operators Report').getByRole('button', { name: 'Buy S$0.80', exact: true })
  if (await meridianBuy.count()) await meridianBuy.click()
  await row('GridScope Asia').getByRole('button', { name: 'Block', exact: true }).click()
  await expect(page.getByText('GridScope blocked: S$1.40 exceeds the remaining S$1.00.').last()).toBeVisible()
  await page.getByRole('button', { name: 'Assemble cited answer' }).click()
  await expect(page.getByText('Dossier ready. Claims are linked to exact accessible spans.').last()).toBeVisible()
  await expect(page.getByText('FIXTURE RESEARCH · NOT INVESTMENT ADVICE')).toBeVisible()
  await expect(page.getByText('≈ S$1.00', { exact: false }).first()).toBeVisible()
})

test('budget control accepts XRP and shows the approximate SGD value', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  const budgetInput = page.locator('input[type="number"][aria-label="Research budget in XRP"]')
  await expect(budgetInput).toHaveValue('0.2')
  await expect(page.getByText('Current XRP', { exact: true })).toBeVisible()
  await expect(page.getByText('Analysis token cap', { exact: false })).toHaveCount(0)
  await expect(page.locator('.budget-sgd')).toHaveText('≈ S$2.00')
  await budgetInput.fill('0.5')
  await expect(page.locator('.budget-sgd')).toHaveText('≈ S$5.00')
  await page.getByRole('button', { name: 'Start research' }).click()
  await expect(page.locator('.topbar-budget')).toHaveText('0.42 XRP left')
})

test('premium evidence is protected until its exact purchase', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  await page.getByRole('button', { name: 'Start research' }).click()
  await page.getByRole('button', { name: /Show .* more sources/ }).click()
  const row = page.locator('.source-row').filter({ hasText: 'Circuit Note' })
  await row.getByRole('button', { name: /Inspect Circuit Note/ }).click()
  await expect(page.getByText('Full text is protected')).toBeVisible()
  await expect(page.getByText('Only metadata, preview, price, and terms are visible before purchase.')).toBeVisible()
  await expect(page.getByText('Two switchgear suppliers said booked orders now extend beyond twelve months')).toHaveCount(0)
})

test('setup stays on the canonical fixture scenario', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Financial Times', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Reuters', { exact: true })).toHaveCount(0)
  await expect(page.getByText('BIS', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /bond market/i })).toHaveCount(0)
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Select fixture source profiles' })).toBeVisible()
  await expect(page.getByText(/synthetic local fixtures/i)).toBeVisible()
})
