import { expect, test } from '@playwright/test'

test('canonical fixture run makes the budget decisions visible', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'What are you trying to find out?' })).toBeVisible()
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  await page.getByLabel('Decision this supports').fill('Invest, wait, or avoid AI infrastructure exposure')
  await page.getByRole('button', { name: 'Start research' }).click()
  await expect(page.getByRole('heading', { name: '20 mock articles ranked' })).toBeVisible()
  await page.getByRole('button', { name: /Show .* more articles/ }).click()
  const row = (name: string) => page.locator('.source-row').filter({ hasText: name })
  await row('Northstar Wire').getByRole('button', { name: 'Buy S$0.20', exact: true }).click()
  await row('Circuit Note').getByRole('button', { name: 'Skip S$0.30', exact: true }).click()
  await row('The Meridian Ledger').getByRole('button', { name: 'Buy S$0.80', exact: true }).click()
  await row('GridScope Asia').getByRole('button', { name: 'Block', exact: true }).click()
  await expect(page.getByText('GridScope blocked: S$1.40 exceeds the remaining S$1.00.').last()).toBeVisible()
  await page.getByRole('button', { name: 'Assemble cited answer' }).click()
  await expect(page.getByText('Dossier ready. Claims are linked to exact accessible spans.').last()).toBeVisible()
  await expect(page.getByText('FIXTURE RESEARCH · NOT INVESTMENT ADVICE')).toBeVisible()
  await expect(page.getByText('S$1.00', { exact: true }).first()).toBeVisible()
})

test('premium evidence is protected until its exact purchase', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  await page.getByRole('button', { name: 'Start research' }).click()
  await page.getByRole('button', { name: /Show .* more articles/ }).click()
  const row = page.locator('.source-row').filter({ hasText: 'Circuit Note' })
  await row.getByRole('button', { name: /Inspect Circuit Note/ }).click()
  await expect(page.getByText('Full text is protected')).toBeVisible()
  await expect(page.getByText('Only metadata, preview, price, and terms are visible before purchase.')).toBeVisible()
  await expect(page.getByText('Two switchgear suppliers said booked orders now extend beyond twelve months')).toHaveCount(0)
})

test('website allowlist narrows mock articles and exposes the x402 boundary', async ({ page }) => {
  await page.goto('/')
  for (const index of [2, 3, 4, 5, 6, 7]) await page.locator('.publisher-option').nth(index).click()
  await page.getByRole('button', { name: 'What is causing the bond market implosion?' }).click()
  await page.getByRole('button', { name: 'Start research' }).click()
  await expect(page.getByRole('heading', { name: '4 mock articles ranked' })).toBeVisible()
  const row = page.locator('.source-row').filter({ hasText: 'Harbour Rates Wire' })
  await row.getByRole('button', { name: /Inspect Harbour Rates Wire/ }).click()
  await expect(page.getByText(/x402 quote · XRPL Testnet fixture/)).toBeVisible()
})
