import { expect, test } from '@playwright/test'

test('canonical fixture run makes the budget decisions visible', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'What economic question deserves a closer look?' })).toBeVisible()
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Make the question answerable.' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Select sources to refer to' })).toBeVisible()
  await page.getByRole('button', { name: 'Start research' }).click()
  await expect(page.getByRole('heading', { name: '20 mock search previews ranked' })).toBeVisible()
  await expect(page.getByRole('heading', { name: /The Meridian Ledger paid and unlocked\./ })).toBeVisible()
  await page.getByRole('button', { name: /Show .* more articles/ }).click()
  const row = (name: string) => page.locator('.source-row').filter({ hasText: name })
  await row('Northstar Wire').getByRole('button', { name: 'Buy S$0.20', exact: true }).click()
  await row('Circuit Note').getByRole('button', { name: 'Skip S$0.30', exact: true }).click()
  const meridianBuy = row('The Meridian Ledger').getByRole('button', { name: 'Buy S$0.80', exact: true })
  if (await meridianBuy.count()) await meridianBuy.click()
  await row('GridScope Asia').getByRole('button', { name: 'Block', exact: true }).click()
  await expect(page.getByText('GridScope blocked: S$1.40 exceeds the remaining S$1.00.').last()).toBeVisible()
  await page.getByRole('button', { name: 'Assemble cited answer' }).click()
  await expect(page.getByText('Dossier ready. Claims are linked to exact accessible spans.').last()).toBeVisible()
  await expect(page.getByText('FIXTURE RESEARCH · NOT INVESTMENT ADVICE')).toBeVisible()
  await expect(page.getByText('≈ S$1.00', { exact: false }).first()).toBeVisible()
})

test('budget control accepts XRP and shows the approximate SGD value', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  const budgetInput = page.locator('input[type="number"][aria-label="Research budget in XRP"]')
  await expect(budgetInput).toHaveValue('0.2')
  await expect(page.getByText('Current XRP', { exact: true })).toBeVisible()
  await expect(page.getByText('Analysis token cap', { exact: false })).toHaveCount(0)
  await expect(page.locator('.budget-sgd')).toHaveText('≈ S$2.00')
  await budgetInput.fill('0.5')
  await expect(page.locator('.budget-sgd')).toHaveText('≈ S$5.00')
  await page.getByRole('button', { name: 'Start research' }).click()
  await expect(page.getByText('0.42 XRP left')).toBeVisible()
})

test('premium evidence is protected until its exact purchase', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Is the AI data-centre investment boom sustainable through 2028?', exact: true }).click()
  await page.getByRole('button', { name: 'Start research' }).click()
  await page.getByRole('button', { name: /Show .* more articles/ }).click()
  const row = page.locator('.source-row').filter({ hasText: 'Circuit Note' })
  await row.getByRole('button', { name: /Inspect Circuit Note/ }).click()
  await expect(page.getByText('Full text is protected')).toBeVisible()
  await expect(page.getByText('Only metadata, preview, price, and terms are visible before purchase.')).toBeVisible()
  await expect(page.getByText('Two switchgear suppliers said booked orders now extend beyond twelve months')).toHaveCount(0)
})

test('website allowlist narrows mock articles and exposes the x402 boundary', async ({ page }) => {
  await page.goto('/')
  for (const index of [2, 3, 4, 5, 6, 7]) await page.locator('.publisher-option').nth(index).click()
  await page.getByRole('button', { name: 'What is causing the bond market implosion?' }).click()
  await page.getByRole('button', { name: 'Start research' }).click()
  await expect(page.getByRole('heading', { name: /mock search previews ranked/ })).toBeVisible()
  const row = page.locator('.source-row').filter({ hasText: 'Credit Spread Watch' })
  await row.getByRole('button', { name: /Inspect Credit Spread Watch/ }).click()
  await expect(page.getByText(/x402 quote · XRPL Testnet fixture/)).toBeVisible()
})
