import { test, expect } from '@playwright/test'

test.describe('FairCut fixture rehearsal', () => {
  test('opens with Leah context and completes the guided state sequence', async ({ page }) => {
    await page.goto('/demo')
    await page.getByRole('button', { name: /Scenario/ }).click()
    await page.getByRole('menuitem', { name: 'Reset demo' }).click()
    await expect(page.getByRole('button', { name: 'Run guided demo' })).toBeVisible()
    await expect(page.getByRole('status')).toBeHidden({ timeout: 7_000 })
    await page.screenshot({ path: 'verification/desktop-initial.png', fullPage: false })
    await expect(page.getByRole('heading', { name: /Leah needs one usable cue/i })).toBeVisible()
    await expect(page.getByText('FIXTURE DEMO', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Run guided demo' })).toBeVisible()
    await page.getByRole('button', { name: 'Run guided demo' }).click()
    await expect(page.getByRole('heading', { name: 'Three cues. One hard boundary.' })).toBeVisible()
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByText('Blocked before signing', { exact: true }).first()).toBeVisible()
    await expect(page.getByText('No transaction was signed or submitted.', { exact: true })).toBeVisible()
    await page.screenshot({ path: 'verification/desktop-blocked.png', fullPage: false })
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByRole('heading', { name: 'Dawn Current — 12s sting', exact: true })).toBeVisible()
    await page.getByRole('button', { name: /License for 8,000 drops/i }).click()
    await expect(page.getByText(/Fixture purchase recorded/)).toBeVisible()
    await page.getByRole('button', { name: /Verify delivered stem/i }).click()
    await expect(page.getByRole('heading', { name: 'Hear the difference.' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Play final cut' })).toBeVisible()
    await page.getByRole('button', { name: 'Open rights receipt' }).click()
    await expect(page.getByRole('dialog', { name: 'Evidence drawer' })).toBeVisible()
    await expect(page.getByText('SIMULATION — NOT SETTLED', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Copy payee address' }).click()
    await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe('rMikaDemoPayee7Q')
    await page.screenshot({ path: 'verification/desktop-receipt.png', fullPage: false })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog', { name: 'Evidence drawer' })).toBeHidden()
  })

  test('keeps the blocked purchase unavailable and supports reset', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/demo')
    await page.getByRole('button', { name: /Scenario/ }).click()
    await page.getByRole('menuitem', { name: 'Reset demo' }).click()
    await expect(page.getByRole('button', { name: 'Run guided demo' })).toBeVisible()
    await expect(page.getByRole('status')).toBeHidden({ timeout: 7_000 })
    await page.screenshot({ path: 'verification/mobile-initial.png', fullPage: false })
    await page.getByRole('button', { name: 'Run guided demo' }).click()
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByRole('button', { name: 'No purchase' })).toBeDisabled()
    await page.getByRole('button', { name: /Scenario/ }).click()
    await page.getByRole('menuitem', { name: 'Reset demo' }).click()
    await expect(page.getByRole('button', { name: 'Run guided demo' })).toBeVisible()
  })

  test('captures mobile blocked, receipt-sheet, and delivery-exception states', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/demo')
    await page.getByRole('button', { name: /Scenario/ }).click()
    await page.getByRole('menuitem', { name: 'Reset demo' }).click()
    await expect(page.getByRole('button', { name: 'Run guided demo' })).toBeVisible()
    await page.getByRole('button', { name: 'Run guided demo' }).click()
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByText('Blocked before signing', { exact: true }).first()).toBeVisible()
    await page.screenshot({ path: 'verification/mobile-blocked.png', fullPage: false })
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByRole('heading', { name: 'Dawn Current — 12s sting', exact: true })).toBeVisible()
    await page.getByRole('button', { name: /Scenario/ }).click()
    await page.getByRole('menuitem', { name: 'Delivery hash mismatch' }).click()
    await expect(page.getByRole('button', { name: 'Run guided demo' })).toBeVisible()
    await page.getByRole('button', { name: 'Run guided demo' }).click()
    await page.getByRole('button', { name: 'Next step' }).click()
    await page.getByRole('button', { name: 'Next step' }).click()
    await page.getByRole('button', { name: /License for 8,000 drops/i }).click()
    await page.getByRole('button', { name: /Verify delivered stem/i }).click()
    await expect(page.locator('.action-section .action-kicker .mono')).toHaveText('FULFILMENT_EXCEPTION')
    await expect(page.getByText(/Payment settled; delivery did not verify/)).toBeVisible()
    await expect(page.getByText(/Retry verification or re-fetch from the provider/)).toBeVisible()
    await page.screenshot({ path: 'verification/mobile-exception.png', fullPage: false })
    await page.getByRole('button', { name: 'Open rights receipt' }).click()
    await expect(page.getByRole('dialog', { name: 'Evidence drawer' })).toBeVisible()
    await page.screenshot({ path: 'verification/mobile-receipt.png', fullPage: false })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog', { name: 'Evidence drawer' })).toBeHidden()
  })
})
